#!/bin/bash

set -e -x

BUILT_RESOURCE=$PWD/built-resource

DOCKER_VERSION=17.09.0-ce

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

cd $(dirname $0)/../..

go install github.com/concourse/docker-image-resource/vendor/github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p -skip "DockerImageResource"

go build -o ./assets/check ./cmd/check/
go build -o ./assets/print-metadata ./cmd/print-metadata/
curl -sSL -O "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz"
tar zxf "docker-${DOCKER_VERSION}.tgz"

go build -o ./ecr-login github.com/concourse/docker-image-resource/vendor/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cmd

cp -a ./* ${BUILT_RESOURCE}/
